modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="paladium"
version="1.0.0"
displayName="Paladium"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mouaw, Toni_4819, MCreator"
description="A Paladium fan mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.paladium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration